<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <RootNamespace>vsbd_core</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
     </PropertyGroup>

    <PropertyGroup>
        <SignAssembly>false</SignAssembly>
        <PublicSign>false</PublicSign>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="NetCord" Version="1.0.0-alpha.429" />
    </ItemGroup>
</Project>
